version: '3.1'

services:
  db:
    image: mysql:8.4.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  server:
    image: python
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./server/DockerfilePython
    restart: always
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000

  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_BASE_URL=${REACT_APP_SERVER_BASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start